version: 2.1

orbs:
  slack: circleci/slack@0.1.1

references:

  container_config: &container_config
    docker:
      - image: circleci/node:8
    working_directory: ~/repo

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v5-repo-{{ .Branch }}-{{ .Revision }}
        - v5-repo-{{ .Branch }}
        - v5-repo

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker:
          docker_layer_caching: true
      - save_cache:
          key: v5-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .
  test:
    <<: *container_config
    steps:
      - *restore_repo
      - run:
          name: yarn install
          command: yarn install
      - run: yarn truffle compile
      - run: yarn ganache-cli > /dev/null & sleep 10 && yarn truffle test

workflows:
  checkout_and_test:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
